import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SocketInitializer from "@/app/components/SocketInitializer";
import SessionProviderWrapper from "@/app/components/SessionProviderWrapper"; // Import client-side wrapper

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: '400'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>
        <SessionProviderWrapper> {/* Wrap in a client component */}
            {children}
            <Toaster position="bottom-right" reverseOrder={false} />
            <SocketInitializer />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
